services:
  web:
    image: ${IMAGE}
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:3000/ >/dev/null 2>&1 || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
