services:
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    env_file:
      - .env
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_CATALOG_MAXENTRIES: 5000
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - registry_data:/var/lib/registry
      - ./module-infra/nginx/.htpasswd:/auth/htpasswd:ro
    networks:
      - depromeet_network

  registry-web:
    image: joxit/docker-registry-ui:latest
    container_name: registry-web
    restart: unless-stopped
    environment:
      REGISTRY_TITLE: "Private Docker Registry"
      REGISTRY_URL: http://registry:5000
      DELETE_IMAGES: "true"
      SHOW_CONTENT_DIGEST: "true"
      SINGLE_REGISTRY: "true"
    depends_on:
      - registry
    networks:
      - depromeet_network

  jenkins:
    image: jenkins/jenkins:2.462.3-lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    user: root
    networks:
      - depromeet_network

volumes:
  registry_data:
    driver: local
  jenkins_home:
    driver: local

networks:
  depromeet_network:
    external: true