services:
  # Private Docker Registry
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    env_file:
      - .env
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_CATALOG_MAXENTRIES: 5000
      # HTTP 설정 (업로드 안정성 향상)
      REGISTRY_HTTP_SECRET: "a-very-long-random-string-for-http-secret"
      REGISTRY_HTTP_TIMEOUT_READ: "300s"
      REGISTRY_HTTP_TIMEOUT_WRITE: "300s"
      REGISTRY_HTTP_TIMEOUT_IDLE: "900s"
      # 스토리지 설정 (업로드 청크 크기 최적화)
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: "inmemory"
      # 로그 레벨
      REGISTRY_LOG_LEVEL: "info"
    volumes:
      - registry_data:/var/lib/registry
      - ./module-infra/nginx/.htpasswd:/auth/htpasswd:ro
    networks:
      - depromeet_network

  registry-web:
    image: hyper/docker-registry-web
    container_name: registry-web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      REGISTRY_URL: http://registry:5000/v2
      REGISTRY_NAME: Depromeet Team 3 Private Docker Registry
      REGISTRY_READONLY: "false"
      REGISTRY_BASIC_AUTH: "ZGVwcm9tZWV0OjEyMzQ="
      REGISTRY_TRUST_ANY_SSL: "true"
    depends_on:
      - registry
    networks:
      - depromeet_network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - TZ=Asia/Seoul
    user: root
    networks:
      - depromeet_network
    mem_limit: 3g        # Jenkins 컨테이너 메모리 제한
    mem_reservation: 1g  # 예약 메모리
    cpus: 2.0

  # Signoz Monitoring Server
  clickhouse:
    image: clickhouse/clickhouse-server:23.11-alpine
    container_name: signoz-clickhouse
    restart: unless-stopped
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
      - ./monitoring/signoz/clickhouse-cluster-config.xml:/etc/clickhouse-server/config.d/cluster.xml:ro
    environment:
      - CLICKHOUSE_DB=signoz_traces
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - depromeet_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  query-service:
    image: signoz/query-service:0.40.0
    container_name: signoz-query-service
    restart: unless-stopped
    command:
      - "-config=/root/config/prometheus.yml"
    volumes:
      - ./monitoring/signoz/prometheus.yml:/root/config/prometheus.yml
      - signoz-data:/var/lib/signoz
    environment:
      - ClickHouseUrl=tcp://clickhouse:9000
      - STORAGE=clickhouse
      - GODEBUG=netdns=go
      - TELEMETRY_ENABLED=true
      - DEPLOYMENT_TYPE=docker-standalone-amd
      - SIGNOZ_JWT_SECRET=momuzzi-signoz-jwt-secret-key-2025    # 임시 값
    networks:
      - depromeet_network
    depends_on:
      clickhouse:
        condition: service_healthy

  signoz-otel-collector:
    image: signoz/signoz-otel-collector:0.88.11
    container_name: signoz-otel-collector
    restart: unless-stopped
    command:
      - "--config=/etc/otel-collector-config.yaml"
    volumes:
      - ./monitoring/signoz/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-host,os.type=linux
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
    networks:
      - depromeet_network
    depends_on:
      clickhouse:
        condition: service_healthy

  signoz-frontend:
    image: signoz/frontend:0.40.0
    container_name: signoz-frontend
    restart: unless-stopped
    ports:
      - "3301:3301"
    networks:
      - depromeet_network
    depends_on:
      - query-service

volumes:
  registry_data:
    driver: local
  jenkins_home:
    driver: local
  clickhouse-data:
    driver: local
  signoz-data:
    driver: local

networks:
  depromeet_network:
    external: true