services:
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    env_file:
      - .env
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - registry_data:/var/lib/registry
      - ./module-infra/nginx/.htpasswd:/auth/htpasswd:ro
    networks:
      - depromeet_network

  registry-web:
    image: hyper/docker-registry-web
    container_name: registry-web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      REGISTRY_URL: http://registry:5000/v2
      REGISTRY_NAME: Depromeet Team 3 Private Docker Registry
      REGISTRY_READONLY: "false"
      REGISTRY_BASIC_AUTH: "${REGISTRY_USERNAME}:${REGISTRY_PASSWORD}"
    depends_on:
      - registry
    networks:
      - depromeet_network

volumes:
  registry_data:
    driver: local

networks:
  depromeet_network:
    external: true