server:
  forward-headers-strategy: native

spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update      # 추후 validate


app:
  env: prod

kakao:
  redirect-uri: # 프론트 도메인

api:
  naver:
    map:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}