server:
  forward-headers-strategy: native

spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update


app:
  env: prod

kakao:
  redirect-uris:
    - http://localhost:3000/auth/callback
    - https://www.momuzzi.site/auth/callback
    - https://api.momuzzi.site/auth/callback
