spring:
  application:
    name: team3-api
  
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/${DEFAULT_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: create

# WAS 헬스 체크 관련
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

api:
  naver:
    map:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}
      geocoding-base-url: https://naveropenapi.apigw.ntruss.com/map-geocode/v2
      local-search-base-url: https://openapi.naver.com/v1/search