spring:
  application:
    name: team3-api
  
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/${DEFAULT_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

# WAS 헬스 체크 관련
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 3600000   # 1시간
  refresh-token-validity: 604800000   # 1주일

# 앱 설정
app:
  env: local

# 카카오 OAuth 설정
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: http://localhost:8080/login/oauth2/code/kakao
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me

api:
  naver:
    map:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}
      geocoding-base-url: https://naveropenapi.apigw.ntruss.com/map-geocode/v2
      local-search-base-url: https://openapi.naver.com/v1/search