server:
  forward-headers-strategy: native

spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create


app:
  env: prod

kakao:
  redirect-uri: http://localhost:3000/auth/callback