receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 10000
    timeout: 10s
  
  # 리소스 속성 추가
  resource:
    attributes:
      - key: service.name
        value: team3-api
        action: upsert
      - key: deployment.environment
        value: production
        action: upsert

exporters:
  clickhousetraces:
    datasource: tcp://clickhouse:9000/
    docker_multi_node_cluster: false
    low_cardinal_exception_grouping: false

  clickhouselogsexporter:
    dsn: tcp://clickhouse:9000/?database=signoz_logs
    timeout: 10s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

  clickhousemetricswrite:
    endpoint: tcp://clickhouse:9000/?database=signoz_metrics
    timeout: 10s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [clickhousetraces, logging]
    
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [clickhousemetricswrite, logging]
    
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [clickhouselogsexporter, logging]